#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else 'work').resolve()
events = ROOT / 'src/main/java/com/mcmoddev/golems/EGEvents.java'
s = events.read_text()
needle = '''\t\t\t\tExtraGolems.LOGGER.info("[EGPORT] golem_count=" + count\n\t\t\t\t\t\t+ " diamond_tag=" + diamondTagged\n\t\t\t\t\t\t+ " diamond_match=" + (diamondMatch == null ? "null" : diamondMatch.identifier()));\n'''
insert = needle + '''\n\t\t\t\t// Exercise the real player construction path: build a Diamond Golem body,\n\t\t\t\t// place the registered Golem Head block, and require onPlace -> trySpawnGolem\n\t\t\t\t// to consume the structure and create an Extra Golem entity.\n\t\t\t\tfinal net.minecraft.server.level.ServerLevel testLevel = event.getServer().overworld();\n\t\t\t\tfinal BlockPos testHead = new BlockPos(0, 250, 0);\n\t\t\t\ttestLevel.getChunk(testHead);\n\t\t\t\tfinal BlockPos body1 = testHead.below(1);\n\t\t\t\tfinal BlockPos body2 = testHead.below(2);\n\t\t\t\tfinal BlockPos armN = body1.north(1);\n\t\t\t\tfinal BlockPos armS = body1.south(1);\n\t\t\t\tfor (BlockPos p : new BlockPos[]{testHead, body1, body2, armN, armS}) {\n\t\t\t\t\ttestLevel.setBlock(p, Blocks.AIR.defaultBlockState(), net.minecraft.world.level.block.Block.UPDATE_ALL);\n\t\t\t\t}\n\t\t\t\ttestLevel.setBlock(body1, Blocks.DIAMOND_BLOCK.defaultBlockState(), net.minecraft.world.level.block.Block.UPDATE_ALL);\n\t\t\t\ttestLevel.setBlock(body2, Blocks.DIAMOND_BLOCK.defaultBlockState(), net.minecraft.world.level.block.Block.UPDATE_ALL);\n\t\t\t\ttestLevel.setBlock(armN, Blocks.DIAMOND_BLOCK.defaultBlockState(), net.minecraft.world.level.block.Block.UPDATE_ALL);\n\t\t\t\ttestLevel.setBlock(armS, Blocks.DIAMOND_BLOCK.defaultBlockState(), net.minecraft.world.level.block.Block.UPDATE_ALL);\n\t\t\t\tfinal net.minecraft.world.phys.AABB testBox = new net.minecraft.world.phys.AABB(testHead).inflate(6.0D);\n\t\t\t\tfinal int before = testLevel.getEntitiesOfClass(GolemBase.class, testBox).size();\n\t\t\t\ttestLevel.setBlock(testHead, EGRegistry.BlockReg.GOLEM_HEAD.get().defaultBlockState(), net.minecraft.world.level.block.Block.UPDATE_ALL);\n\t\t\t\tfinal int after = testLevel.getEntitiesOfClass(GolemBase.class, testBox).size();\n\t\t\t\tfinal boolean structureConsumed = testLevel.getBlockState(testHead).isAir()\n\t\t\t\t\t\t&& testLevel.getBlockState(body1).isAir()\n\t\t\t\t\t\t&& testLevel.getBlockState(body2).isAir()\n\t\t\t\t\t\t&& testLevel.getBlockState(armN).isAir()\n\t\t\t\t\t\t&& testLevel.getBlockState(armS).isAir();\n\t\t\t\tfinal boolean actualBuild = after > before && structureConsumed;\n\t\t\t\tExtraGolems.LOGGER.info("[EGPORT] actual_build=" + actualBuild\n\t\t\t\t\t\t+ " spawned=" + (after > before)\n\t\t\t\t\t\t+ " structure_consumed=" + structureConsumed\n\t\t\t\t\t\t+ " before=" + before + " after=" + after);\n'''
if needle not in s:
    raise SystemExit('Expected observable EGPORT matcher log not found')
events.write_text(s.replace(needle, insert, 1))
print('Applied real Golem Head placement construction runtime test pass 13')
