from pathlib import Path

p = Path('project/src/main/java/com/mcmoddev/golems/test/VillageRuntimeParityGameTest.java')
s = p.read_text()
old = '''    @GameTest(template = FabricGameTest.EMPTY_STRUCTURE, timeoutTicks = 80)\n    public void realTConstructedBedrockUsesRuntimeVillageReputation(final GameTestHelper helper) {\n        final GolemBase bedrock = constructFromT(helper, Blocks.BEDROCK, new BlockPos(6, 20, 6));\n        helper.assertTrue(!bedrock.isPlayerCreated(), "Fresh T-built Bedrock ended PlayerCreated=true after finalizeSpawn");\n        final Villager villager = addVillager(helper, bedrock.getX(), bedrock.getY(), bedrock.getZ() + 1.0D);\n        final ServerPlayer player = makeListedSurvivalPlayer(helper, "BedrockFreshRuntimeRep");\n        player.setPos(bedrock.getX() + 7.0D, bedrock.getY(), bedrock.getZ());\n        villager.getGossips().add(player.getUUID(), GossipType.MAJOR_NEGATIVE, 25);\n        helper.assertTrue(villager.getPlayerReputation(player) <= -100, "Bedrock reputation setup did not cross vanilla threshold");\n        tickUntilPlayerTarget(bedrock, player);\n        final boolean targeted = bedrock.getTarget() == player;\n        cleanupPlayer(helper, player); villager.discard(); bedrock.discard();\n        helper.assertTrue(targeted, "REAL T-built Bedrock did not runtime-target its low-reputation player");\n        helper.succeed();\n    }\n'''
new = '''    @GameTest(template = FabricGameTest.EMPTY_STRUCTURE, timeoutTicks = 80)\n    public void bedrockSpawnPathUsesRuntimeVillageReputation(final GameTestHelper helper) {\n        // Bedrock is hidden and intentionally has no T-shape building recipe. Exercise\n        // its real generic entity/spawn-finalization path instead.\n        final GolemBase bedrock = GolemBase.create(helper.getLevel(),\n                net.minecraft.resources.ResourceLocation.fromNamespaceAndPath("golems", "bedrock"));\n        helper.assertTrue(bedrock != null, "Failed to create Bedrock Golem");\n        bedrock.moveTo(helper.absolutePos(new BlockPos(6, 20, 6)), 0.0F, 0.0F);\n        bedrock.setNoGravity(true);\n        helper.getLevel().addFreshEntity(bedrock);\n        bedrock.finalizeSpawn(helper.getLevel(), helper.getLevel().getCurrentDifficultyAt(bedrock.blockPosition()),\n                net.minecraft.world.entity.MobSpawnType.MOB_SUMMONED, null);\n        // Let Bedrock's compatibility migration execute exactly as it does on-server.\n        bedrock.tick();\n        helper.assertTrue(!bedrock.isPlayerCreated(), "Bedrock spawn path ended PlayerCreated=true");\n\n        final Villager villager = addVillager(helper, bedrock.getX(), bedrock.getY(), bedrock.getZ() + 1.0D);\n        final ServerPlayer player = makeListedSurvivalPlayer(helper, "BedrockFreshRuntimeRep");\n        player.setPos(bedrock.getX() + 7.0D, bedrock.getY(), bedrock.getZ());\n        villager.getGossips().add(player.getUUID(), GossipType.MAJOR_NEGATIVE, 25);\n        helper.assertTrue(villager.getPlayerReputation(player) <= -100, "Bedrock reputation setup did not cross vanilla threshold");\n        tickUntilPlayerTarget(bedrock, player);\n        final boolean targeted = bedrock.getTarget() == player;\n        cleanupPlayer(helper, player); villager.discard(); bedrock.discard();\n        helper.assertTrue(targeted, "Bedrock actual spawn path did not runtime-target its low-reputation player");\n        helper.succeed();\n    }\n'''
if s.count(old) != 1:
    raise SystemExit('Bedrock T-build test block not found exactly once')
p.write_text(s.replace(old, new, 1))
print('Changed Bedrock parity fixture from invalid T-build to actual spawn/finalize path.')
